version: '3'

services:
  gcalvault:
    build: .
    environment:
      - "CLIENT_ID=<>"
      - "CLIENT_SECRET=<>"
      - "NO_CACHE=true"
      - "EXECAT=* * * * *"
    volumes:
#      - "<ssh-key>:/app/ssh-key:ro"
      - "./data:/app/output"
      - "./gcalvault:/app/conf"
